let chainesAvantARCOM = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "Arte",
    "C8",
    "W9",
    "TMC",
    "TFX",
    "NRJ12",
    "France 4",
    "BFM TV",
    "CNews",
    "CStar",
    "Gulli",
    "TF1 Series Films",
    "6ter",
    "RMC Story",
    "RMC Decouverte",
    "Cherie 25",
    "LCI",
    "FranceInfo"
];

let chainesApresARCOM = [
    "TF1",
    "France 2",
    "France 3",
    "France 4",
    "France 5",
    "M6",
    "Arte",
    "W9",
    "TMC",
    "TFX",
    "Gulli",
    "BFM TV",
    "CNews",
    "LCI",
    "FranceInfo",
    "CStar",
    "T18",
    "TF1 Series Films",
    "6ter",
    "RMC Story",
    "RMC Decouverte",
    "Cherie 25",
    "Canal+"
]